spring:
  application:
    name: ms-students
  datasource:
    url: jdbc:mysql://localhost:3306/students?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: students
    password: students
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true

  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      group-id: student_ms
      properties:
        schema:
          registry:
            url: http://127.0.0.1:8081
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: student_ms
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema:
          registry:
            url: http://127.0.0.1:8081
        specific:
          avro:
            reader: true
      acks: MANUAL_IMMEDIATE

kafka:
  topic:
    student-created:
      name: StudentCreated
      partitions: 10
      replicas: 1
    student-course-created:
      name: StudentCourseCreated
      partitions: 10
      replicas: 1


