/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.schema.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class StudentMessageInput extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4863304256732883050L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StudentMessageInput\",\"namespace\":\"com.example.schema.avro\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"birthday\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.DateConversion());
  }

  private static final BinaryMessageEncoder<StudentMessageInput> ENCODER =
      new BinaryMessageEncoder<StudentMessageInput>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StudentMessageInput> DECODER =
      new BinaryMessageDecoder<StudentMessageInput>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StudentMessageInput> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StudentMessageInput> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StudentMessageInput> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<StudentMessageInput>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StudentMessageInput to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StudentMessageInput from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StudentMessageInput instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StudentMessageInput fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String name;
   private java.time.LocalDate birthday;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StudentMessageInput() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param birthday The new value for birthday
   */
  public StudentMessageInput(java.lang.String name, java.time.LocalDate birthday) {
    this.name = name;
    this.birthday = birthday;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return birthday;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      new org.apache.avro.data.TimeConversions.DateConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = value$ != null ? value$.toString() : null; break;
    case 1: birthday = (java.time.LocalDate)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }



  /**
   * Gets the value of the 'birthday' field.
   * @return The value of the 'birthday' field.
   */
  public java.time.LocalDate getBirthday() {
    return birthday;
  }



  /**
   * Creates a new StudentMessageInput RecordBuilder.
   * @return A new StudentMessageInput RecordBuilder
   */
  public static com.example.schema.avro.StudentMessageInput.Builder newBuilder() {
    return new com.example.schema.avro.StudentMessageInput.Builder();
  }

  /**
   * Creates a new StudentMessageInput RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StudentMessageInput RecordBuilder
   */
  public static com.example.schema.avro.StudentMessageInput.Builder newBuilder(com.example.schema.avro.StudentMessageInput.Builder other) {
    if (other == null) {
      return new com.example.schema.avro.StudentMessageInput.Builder();
    } else {
      return new com.example.schema.avro.StudentMessageInput.Builder(other);
    }
  }

  /**
   * Creates a new StudentMessageInput RecordBuilder by copying an existing StudentMessageInput instance.
   * @param other The existing instance to copy.
   * @return A new StudentMessageInput RecordBuilder
   */
  public static com.example.schema.avro.StudentMessageInput.Builder newBuilder(com.example.schema.avro.StudentMessageInput other) {
    if (other == null) {
      return new com.example.schema.avro.StudentMessageInput.Builder();
    } else {
      return new com.example.schema.avro.StudentMessageInput.Builder(other);
    }
  }

  /**
   * RecordBuilder for StudentMessageInput instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StudentMessageInput>
    implements org.apache.avro.data.RecordBuilder<StudentMessageInput> {

    private java.lang.String name;
    private java.time.LocalDate birthday;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.schema.avro.StudentMessageInput.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.birthday)) {
        this.birthday = data().deepCopy(fields()[1].schema(), other.birthday);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing StudentMessageInput instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.schema.avro.StudentMessageInput other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.birthday)) {
        this.birthday = data().deepCopy(fields()[1].schema(), other.birthday);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.example.schema.avro.StudentMessageInput.Builder setName(java.lang.String value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.example.schema.avro.StudentMessageInput.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'birthday' field.
      * @return The value.
      */
    public java.time.LocalDate getBirthday() {
      return birthday;
    }


    /**
      * Sets the value of the 'birthday' field.
      * @param value The value of 'birthday'.
      * @return This builder.
      */
    public com.example.schema.avro.StudentMessageInput.Builder setBirthday(java.time.LocalDate value) {
      validate(fields()[1], value);
      this.birthday = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'birthday' field has been set.
      * @return True if the 'birthday' field has been set, false otherwise.
      */
    public boolean hasBirthday() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'birthday' field.
      * @return This builder.
      */
    public com.example.schema.avro.StudentMessageInput.Builder clearBirthday() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StudentMessageInput build() {
      try {
        StudentMessageInput record = new StudentMessageInput();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.String) defaultValue(fields()[0]);
        record.birthday = fieldSetFlags()[1] ? this.birthday : (java.time.LocalDate) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StudentMessageInput>
    WRITER$ = (org.apache.avro.io.DatumWriter<StudentMessageInput>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StudentMessageInput>
    READER$ = (org.apache.avro.io.DatumReader<StudentMessageInput>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










